name: Container Build Testing

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker Build Check
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest

    - name: Build image
      env: 
        DOCKER_FOLDER: "object-ledger"
      run: |
        docker buildx build $DOCKER_FOLDER \
        --platform linux/arm64,linux/amd64